import React from 'react';
import { useNavigate } from 'react-router-dom'

const About = () => {
    const navigate = useNavigate();
  return (
    <div>
        <h3>About checkoutscing elit. Morbi condimentum sem porta leo interdum, vitae gravida nisi consectetur. Sed nec hendrerit leo. Mauris sodales odio vitae volutpat facilisis. Donec convallis commodo lorem eu ultrices. Sed vulputate nunc at purus molestie, nec gravida odio posuere. Duis maximus nunc maximus, ornare nisi nec, efficitur felis. Nullam eu ipsum venenatis, gravida ipsum quis, ultricies diam. Maecenas faucibus dolor in lectus tristique, sed pulvinar erat dapibus. Suspendisse tincidunt nibh eu nisi ornare, quis iaculis ipsum pharetra. Donec cursus tincidunt placerat. Suspendisse potenti.

Phasellus ac lorem vel nisi molestie tincidunt quis ut tortor. Fusce leo ligula, facilisis sit amet feugiat quis, efficitur eu turpis. Duis in magna vitae magna ornare venenatis. Ut vehicula porttitor arcu vel hendrerit. Nullam congue ullamcorper pellentesque. Sed elementum accumsan ex, nec consequat eros scelerisque eu. Integer quis tempor libero. Ut quis ligula cursus, gravida velit id, viverra augue. Etiam lacinia enim in felis finibus, ut vehicula ex iaculis. Pellentesque sed euismod nulla, sit amet vestibulum nisl. Nam a metus blandit, sagittis nisl ac, aliquet quam. Sed sit amet libero at diam commodo tempor.

Sed ut lacus faucibus, porttitor nulla nec, consectetur velit. Vestibulum convallis tincidunt dolor ut placerat. Morbi purus justo, pulvinar sit amet porta vitae, convallis nec justo. Donec id viverra lorem. Morbi venenatis enim eu pharetra imperdiet. Aenean elementum rutrum scelerisque. In ipsum velit, finibus porttitor semper ut, lacinia ac nisi. Curabitur nec libero at enim finibus pellentesque.

Morbi risus justo, dapibus sed nulla nec, lobortis egestas tortor. Phasellus pulvinar consequat mauris. Donec at suscipit urna. Donec blandit est metus, nec faucibus arcu auctor et. Suspendisse facilisis ligula nisi, non fringilla libero tincidunt sed. Aenean vehicula urna porttitor pellentesque volutpat. Integer scelerisque metus quis gravida condimentum. Nulla dignissim interdum diam, id hendrerit neque volutpat non. Sed laoreet aliquam augue, id tincidunt dui convallis et. Donec vulputate erat quis eleifend faucibus. Mauris venenatis molestie mi nec lobortis. Aenean commodo, justo sed sollicitudin dictum, metus elit sollicitudin tortor, ut posuere lorem tortor vitae risus.

Nunc suscipit enim vel dui pulvinar elementum. Etiam commodo dignissim massa, id aliquet eros facilisis vitae. Donec congue maximus libero in eleifend. Sed maximus sed augue ac congue. Aenean scelerisque neque quis libero dapibus, non rhoncus est viverra. Aenean gravida pulvinar pharetra. Fusce congue mi vel ipsum efficitur dictum eget id odio. Maecenas lorem est, tempor quis metus nec, condimentum venenatis diam. Nam iaculis vulputate nunc eget convallis. Curabitur et eros convallis, gravida erat id, imperdiet velit. Duis pellentesque fringilla ipsum id pellentesque. Integer id nunc sit amet odio porttitor pellentesque eu et dui. In venenatis dictum magna, non venenatis sem congue in. Fusce nulla tortor, sodales at mauris quis, faucibus volutpat magna. Aliquam posuere molestie rhoncus.

Quisque id feugiat felis. Ut vitae neque cursus mi suscipit feugiat ac in lorem. Donec euismod sit amet nibh nec efficitur. Sed quis consequat turpis, quis vulputate diam. Vestibulum aliquet, lectus at lobortis cursus, quam quam fermentum nisi, at ultricies dui dui eget mauris. Sed eget pharetra lorem. Praesent pellentesque, odio et finibus sollicitudin, felis justo sodales nunc, eget aliquam orci urna at lectus. Aenean mauris sapien, rhoncus quis eros eu, sollicitudin convallis purus. Etiam dignissim dolor varius tincidunt facilisis. Etiam in tempus felis.

Suspendisse turpis sem, bibendum eget velit quis, ullamcorper molestie nisi. Suspendisse lobortis ex leo, nec porta elit semper vitae. Vivamus gravida dui in massa finibus, nec tincidunt purus sodales. Vivamus sollicitudin lectus quis metus ultrices, consequat sollicitudin libero molestie. Ut eget pulvinar mauris. Nunc pulvinar ultricies tellus iaculis vulputate. Aenean dui orci, aliquam in mi nec, pretium congue quam. Sed dapibus mattis accumsan. Vestibulum felis leo, ultricies id sodales vitae, suscipit sed est. Suspendisse pretium magna nec erat tempor, sit amet gravida nisi pretium. Sed porta finibus porta. Donec nec interdum lectus.

Aliquam condimentum urna vitae orci maximus, vitae pharetra massa bibendum. Etiam sed orci vitae ante venenatis imperdiet. Ut metus est, dapibus sit amet nisi at, cursus imperdiet turpis. In non risus dapibus, eleifend velit vitae, pharetra nunc. Ut sodales sed nunc vitae vulputate. Curabitur tempus metus vel metus porta sagittis eu vel augue. Curabitur dapibus mattis fermentum. Vestibulum vulputate, erat at accumsan pretium, felis libero maximus lacus, sit amet rutrum risus augue non urna. Quisque vitae est porttitor, suscipit nunc nec, auctor sem. Cras aliquet enim eu nibh rhoncus, nec pharetra ligula semper. Phasellus ac enim sed mi sagittis elementum a sed libero.

Proin scelerisque faucibus orci nec elementum. Praesent blandit, mi at semper accumsan, ante velit commodo lorem, id elementum dui lacus id nunc. Sed ullamcorper, augue at convallis aliquam, nulla sem fringilla leo, non semper mi nulla a erat. Cras rutrum aliquet orci, ut interdum ipsum dictum ut. Duis egestas, lectus vulputate luctus mollis, lectus nisl accumsan ipsum, sed venenatis odio turpis in elit. Morbi suscipit dictum ornare. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis justo metus, cursus eu erat sit amet, lacinia mattis lacus. Suspendisse imperdiet fringilla nulla ut tincidunt. Praesent fringilla bibendum eleifend. Nunc ornare egestas sem. Nunc imperdiet iaculis orci, nec tincidunt ligula lobortis sit amet. Curabitur libero massa, mollis sit amet aliquam nec, mattis dapibus elit. Quisque at elit vel dui gravida sollicitudin. Ut vitae mi mi.

Vivamus consequat interdum dapibus. Proin ac suscipit ipsum, at commodo sapien. Vestibulum id tincidunt mi. Praesent aliquam pellentesque velit, ut aliquet diam porttitor aliquam. Sed accumsan magna nec arcu consequat malesuada. Etiam porttitor dui nibh, eget faucibus ante iaculis vel. Phasellus eget ornare nisi. Sed rhoncus lectus urna, sit amet varius nunc ullamcorper vel. Maecenas sed dignissim erat, pharetra dapibus nibh. In sollicitudin dui orci, eu varius lacus dictum sed. Nullam id ornare dui. Cras pulvinar mauris eget erat vestibulum malesuada. Nunc feugiat quis sapien id rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Interdum et malesuada fames ac ante ipsum primis in faucibus. In ex nisl, facilisis sit amet nibh vitae, mollis ultrices libero.

Nullam elementum, diam id placerat rutrum, sapien urna dictum leo, auctor eleifend ex mauris eu dui. Nulla facilisi. Nulla venenatis pulvinar dolor euismod facilisis. Phasellus odio mauris, vehicula id interdum et, sodales et orci. Sed ut aliquam tellus. Duis gravida nunc eu mi efficitur, a malesuada arcu molestie. Morbi cursus dictum nisi sit amet aliquet. Suspendisse cursus sit amet eros eu ultrices. Sed eu tincidunt ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas ornare est sit amet dui mattis pharetra. Etiam condimentum ac velit nec ornare.

Morbi volutpat aliquam lectus, vitae scelerisque massa tincidunt id. Donec vel volutpat nunc. Donec ornare, odio sit amet facilisis mattis, nulla purus dapibus enim, vel sagittis risus eros sit amet diam. Mauris efficitur ante sit amet gravida luctus. Phasellus pulvinar mattis convallis. Morbi in gravida nibh. Aenean dolor est, lacinia eu pellentesque eget, iaculis et nunc. Vestibulum molestie nisi faucibus mauris pulvinar placerat. Donec dignissim, ipsum sit amet imperdiet maximus, ante odio fermentum ex, vel lacinia dolor tortor vitae lorem. Nam sed interdum leo. Suspendisse bibendum tincidunt lectus, quis cursus justo pretium vel. Fusce rutrum ullamcorper mi ut lobortis. Sed sit amet lorem facilisis, cursus purus in, dapibus massa. Sed maximus mi quis ornare placerat.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse a mauris ut urna tincidunt porttitor. Integer tristique, odio sit amet ultrices rutrum, velit lectus lacinia dui, a luctus augue augue et tellus. Maecenas pellentesque interdum porttitor. Sed sit amet mi ac lacus molestie pulvinar. Proin vel eros sapien. Suspendisse vel tempor nibh, in porttitor est. Curabitur laoreet pharetra dui malesuada interdum. Praesent venenatis elementum accumsan. In pulvinar mi ut dui porta, in cursus orci porta. Etiam a facilisis nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam mattis orci vel sem fringilla elementum. Sed eget feugiat purus.

Duis vitae mattis libero. Nullam lacinia eget sem eu mattis. Duis iaculis id velit vel egestas. Curabitur maximus lorem eget ipsum imperdiet, ut elementum mi porta. Sed vulputate venenatis ante, condimentum lacinia ipsum tempor non. Curabitur in ante tortor. Aliquam semper dictum ante at molestie. Nullam sit amet cursus tortor. Duis efficitur facilisis justo, eget dictum quam sagittis a. Vestibulum magna libero, molestie id tellus et, tempus dictum mauris. Vivamus vel eros vitae magna tincidunt bibendum. Donec commodo erat eros, at consequat augue dapibus sed. Mauris maximus, tellus eget molestie dignissim, lectus enim tempus purus, vitae hendrerit nibh sem quis sapien. Vivamus elementum mi at augue egestas egestas.

Fusce euismod bibendum dui eget luctus. Proin ac placerat est. Vestibulum quam massa, elementum at turpis vel, consectetur viverra tortor. Maecenas ultrices tellus in pellentesque dapibus. Aliquam sed orci egestas, sollicitudin mauris eu, accumsan justo. Fusce quis tincidunt neque. Vivamus consectetur sagittis eleifend. Aliquam eu placerat metus.

Etiam et vulputate quam. Donec vitae iaculis risus, vel tempus massa. Suspendisse lobortis eget leo eget scelerisque. Phasellus dolor tellus, consequat scelerisque elit eu, blandit malesuada orci. Nam ornare eros et commodo lacinia. Aliquam erat volutpat. Suspendisse ac nisi sollicitudin, scelerisque lectus in, hendrerit nisl. Suspendisse placerat cursus risus, molestie rhoncus ligula sodales id. Etiam eu commodo elit, vitae blandit nulla. Sed lorem ante, sodales ut semper sit amet, lacinia id metus. Nulla ullamcorper risus vitae tempor dictum. Vestibulum vitae velit rutrum, consectetur erat ut, mollis leo. Duis in sapien neque.

Aliquam accumsan massa ipsum, pretium auctor ante blandit nec. Quisque suscipit elit bibendum ex luctus cursus. Phasellus facilisis imperdiet dignissim. Etiam et neque at odio malesuada finibus nec laoreet erat. Nunc placerat sapien orci, non viverra quam auctor a. Morbi euismod sagittis massa. Nam efficitur volutpat nulla at sodales. Integer mattis vulputate nisl mattis viverra. Morbi finibus nec nisi vel dictum. Donec vulputate porttitor risus, sed accumsan elit porttitor a. Nunc semper ligula nunc, in porta eros vulputate eget. Aliquam consectetur eget ante id gravida. Cras non imperdiet nulla, a aliquet orci.

Nullam a nulla enim. Nullam ultrices mi arcu, non ultricies risus pellentesque et. Duis ut odio nec odio tincidunt varius vitae elementum ligula. Maecenas et augue nunc. Donec sollicitudin feugiat metus. Cras dolor massa, commodo convallis eleifend vitae, accumsan non enim. Vivamus fringilla commodo porta. Donec facilisis dolor eget turpis volutpat, quis auctor lorem vulputate. Pellentesque quis turpis et massa posuere posuere ac quis tellus.

Nam ullamcorper, magna in accumsan laoreet, nibh urna sollicitudin dolor, non sodales ipsum eros faucibus ligula. Cras tincidunt convallis dui. Mauris auctor elementum euismod. Sed urna lacus, bibendum vitae porta sed, eleifend ut nulla. Vivamus mollis tempor dapibus. Nam scelerisque tempus varius. Praesent ultrices a leo ut feugiat. In vel augue efficitur nunc pellentesque lobortis.

In quis placerat nulla. Integer eget dolor efficitur, dictum odio eu, placerat lectus. Nunc sit amet eros a nulla sollicitudin bibendum. Aliquam erat volutpat. Proin rutrum massa a tortor tincidunt porta. Donec sed sagittis tellus. Cras feugiat massa lacus, at posuere neque porta vitae. Cras vel justo justo.

Duis volutpat dictum risus a placerat. Nunc eleifend, risus sed tincidunt posuere, risus lorem lobortis libero, sit amet luctus ligula dolor ac tellus. Aenean ac ipsum nec nulla vestibulum vehicula vel sed tortor. Nunc porttitor magna ac augue dapibus, nec aliquam erat interdum. Donec eget urna ut tortor tristique tincidunt. Proin varius molestie quam, id fringilla massa dapibus at. Aenean nec pellentesque metus, vel cursus risus. Etiam vel nisl orci. Cras ullamcorper tincidunt lobortis. Etiam in augue non metus laoreet ultrices quis id purus. In quis rutrum sapien, quis finibus nulla. Ut scelerisque lorem nec fermentum malesuada. Donec lorem nisi, pretium id euismod sed, ullamcorper eget eros. Curabitur dictum eleifend consectetur. Fusce vitae justo sed elit vulputate volutpat. Etiam eget nisl sed nisi viverra hendrerit.

Cras euismod lacus sapien, quis suscipit dui interdum eget. Donec id risus nisi. Etiam gravida faucibus tortor et dictum. In tempor auctor massa, et rutrum urna malesuada a. Etiam ac euismod est, ac aliquam sem. Aliquam imperdiet sagittis diam, in suscipit erat venenatis faucibus. Sed lacinia, est quis ullamcorper bibendum, velit quam aliquet tellus, et scelerisque mauris nibh sed leo. Curabitur auctor, ante eu tristique lobortis, erat nibh efficitur augue, nec convallis purus nibh vel elit. Vestibulum cursus, tellus et convallis faucibus, nisi risus vestibulum justo, ac commodo tortor dolor eget tellus. Nullam imperdiet orci eget maximus euismod. Aenean vestibulum mollis ipsum, quis imperdiet felis dictum ac. Phasellus sit amet sapien non ligula ornare commodo sit amet eget velit. Ut consequat blandit sem, pulvinar congue arcu rutrum et. In eget dictum dolor, sed suscipit risus. Donec mattis consectetur odio nec interdum. Maecenas tincidunt mollis auctor.


        </h3>
        <button onClick={()=>navigate(-1,{replace:true})}>Go back</button>
    </div>
  )
}

export default About